### ISSUE TITLE
Parcelable implementation is losing ID value coming through the callback

### ISSUE THREAD

**Issue by s3hengwu** [afollestad/inline-activity-result#2]
I have a model:
@Parcelize
@Entity
data class Relationship(
    val name: String
) : Parcelable {
    @PrimaryKey(autoGenerate = true)
    var id: Long = 0
}

Relationship:id=8,name="Tom", But onResult id=0, name="Tom"

**Comment by afollestad** [comment]
The title and description don't at all hint at anything in this library. 

What exactly is the bug here?

**Comment by s3hengwu** [comment]
setResult:
![11](https://user-images.githubusercontent.com/8500025/78625467-b68c7880-78be-11ea-9a74-f9604531d5cd.png)
onActivityResult:
![22](https://user-images.githubusercontent.com/8500025/78625472-b7bda580-78be-11ea-8617-d4f180bdabd2.png)

**Comment by afollestad** [comment]
I have doubts this is related to this library 🙂 it does not modify `Bundle`'s, they are passed as-is through the callback.
